name: Node.js CI

on:
  push:
    branches-ignore:
      - gh-pages

env:
  CODECOV_TOKEN:
  NPM_CONFIG_LOGLEVEL: error
  NPM_CONFIG_JOBS: max
  NPM_CONFIG_PROGRESS: false

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Cache node_modules/.cache
        uses: actions/cache@v1
        with:
          path: node_modules/.cache
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-job-id-${{ github.job }}-run-id-${{ github.run_id }}
          restore-keys: |
            node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-job-id-${{ github.job }}-
            node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-
      - run: npx eslint . --cache --cache-location node_modules/.cache/eslint --ignore-path .gitignore
      - run: npx stylelint '**/*.css' --cache --cache-location node_modules/.cache/eslint --ignore-path .gitignore
      - run: npx webpack --config webpack.production.js
      - run: npx jest --maxWorkers 2 --coverage --ci
      - run: npx codecov

  publish-storybook-to-gh-pages:
    if: github.ref == 'refs/heads/master'

    needs: test

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    env:
      STORYBOOK_PUBLIC_PATH: /github-actions-workflow-templates/ # replace `github-actions-workflow-templates` with your repository name

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - name: Cache node_modules/.cache
        uses: actions/cache@v1
        with:
          path: node_modules/.cache
          key: node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-job-id-${{ github.job }}-run-id-${{ github.run_id }}
          restore-keys: |
            node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-job-id-${{ github.job }}-
            node-modules-cache-os-${{ runner.os }}-node-${{ matrix.node-version }}-package-lock-${{ hashFiles('package-lock.json') }}-
      - run: npm run storybook:build -- --quiet
      - run: npx storybook-to-ghpages --existing-output-dir=storybook-static --ci
        env:
          GH_TOKEN: jonathanong:${{ secrets.GITHUB_TOKEN }} # replace `jonathanong` with your organization
